# Generated by Django 3.0.2 on 2020-03-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200315_0359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User Accounts'},
        ),
    ]
