# Generated by Django 3.0.2 on 2020-03-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200308_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='goto generate page', max_length=100),
        ),
    ]
