# Generated by Django 3.0.2 on 2020-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200309_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.URLField(blank=True, help_text='goto generate page', max_length=500),
        ),
    ]
