# Generated by Django 3.0.2 on 2020-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200309_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news_id',
            field=models.IntegerField(),
        ),
    ]
