# Generated by Django 3.0.2 on 2020-03-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_news_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='news_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='owner'),
            preserve_default=False,
        ),
    ]
