# Generated by Django 3.0.2 on 2020-03-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200309_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='news_image', to='news.Comments'),
        ),
    ]
