# Generated by Django 3.0.2 on 2020-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200309_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='news_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
