# Generated by Django 3.0.2 on 2020-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_comments_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news_id',
            field=models.IntegerField(editable=False),
        ),
    ]
