# Generated by Django 3.0.2 on 2020-03-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0018_auto_20200311_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='news.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=700)),
                ('contact', models.TextField(blank=True, max_length=10000, null=True)),
                ('about', models.TextField(blank=True, max_length=10000, null=True)),
                ('profile', models.TextField(blank=True, max_length=10000, null=True)),
                ('website', models.URLField()),
                ('date_established', models.DateField()),
                ('banner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blocs_banner', to='news.Media')),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blocs_logo', to='news.Media')),
                ('members', models.ManyToManyField(related_name='bloc_members', to='nugs.Member')),
            ],
        ),
    ]
