# Generated by Django 3.0.2 on 2020-03-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloc',
            old_name='about',
            new_name='history',
        ),
    ]
