# Generated by Django 3.0.2 on 2020-03-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200311_0648'),
        ('nugs', '0002_auto_20200315_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='gallery',
            field=models.ManyToManyField(related_name='bloc_gallery', to='news.Media'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='banner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_banner', to='news.Media'),
        ),
        migrations.AlterField(
            model_name='bloc',
            name='logo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_logo', to='news.Media'),
        ),
    ]
