# Generated by Django 3.0.2 on 2020-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0003_auto_20200308_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1000)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=3)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('featured', models.BooleanField(default=False)),
                ('unlimited', models.BooleanField(default=False)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], max_length=50)),
                ('category', models.CharField(choices=[('Book', 'Book'), ('Shirt', 'Shirt'), ('Cap', 'Cap')], max_length=50)),
                ('image', models.ManyToManyField(related_name='product_image', to='news.Media')),
            ],
        ),
    ]
