# Generated by Django 3.0.2 on 2020-03-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=24.1, max_digits=8),
            preserve_default=False,
        ),
    ]
