# Generated by Django 3.0.2 on 2020-03-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200315_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(help_text='goto https://htmlcolorcodes.com/color-names/ and pick appropriate color code eg.FF0000 for red', max_length=50, unique=True),
        ),
    ]
