# Generated by Django 3.0.2 on 2020-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200315_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(help_text='goto https://htmlcolorcodes.com/color-names/ and pick appropriate color code without # sign eg.FF0000 for red. its very import that you get this right', max_length=6, unique=True),
        ),
    ]
