# Generated by Django 3.0.2 on 2020-04-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Completed', 'Conpleted')], max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_delivered', to='shop.TrackItem')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_product', to='shop.Order')),
                ('ordered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_ordered', to='shop.TrackItem')),
                ('packed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_packed', to='shop.TrackItem')),
                ('shipped', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_shipped', to='shop.TrackItem')),
            ],
        ),
    ]
