# Generated by Django 3.0.2 on 2020-04-04 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_tracking_trackitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackitem',
            name='type',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
