# Generated by Django 3.0.2 on 2020-04-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_trackitem_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackItem',
            new_name='TrackingItem',
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'Tracking', 'verbose_name_plural': 'Trackings'},
        ),
        migrations.AlterModelOptions(
            name='trackingitem',
            options={'verbose_name': 'Tracking Item', 'verbose_name_plural': 'Tracking Items'},
        ),
    ]
