# Generated by Django 3.0.2 on 2020-04-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200404_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='1', max_length=500),
        ),
    ]
